// CF Bossnusilelo V2 — Living 789 Auto Brain
const http=require('http');const path=require('path');const fs=require('fs');const os=require('os');const {execFileSync}=require('child_process');
let chatRouter=require(path.join(__dirname,'api/chat.js'));
const HTML_FILE=path.join(__dirname,'public','index.html');
const CHAT_FILE=path.join(__dirname,'public','chat-living-789-auto.html');
const BACKUP_DIR=path.join(__dirname,'public','backups');
function wrapRes(res){return{setHeader:(k,v)=>res.setHeader(k,v),status:function(c){res.statusCode=c;return this},json:function(o){res.writeHead(res.statusCode||200,{'Content-Type':'application/json'});res.end(JSON.stringify(o))}}}
function sysInfo(){const total=os.totalmem(),free=os.freemem();let disk={total:null,free:null};try{const st=fs.statfsSync(__dirname);disk={total:st.blocks*st.bsize,free:st.bfree*st.bsize}}catch{}const gb=n=>n==null?null:Math.round(n/1073741824*10)/10;return{pid:process.pid,node:process.version,platform:os.platform()+' '+os.release(),arch:os.arch(),uptime:Math.round(process.uptime()),cpu:{load1:os.loadavg()[0],cores:os.cpus().length,model:os.cpus()[0]?.model?.trim()},ram:{total:gb(total),free:gb(free),used:gb(total-free),pct:Math.round((total-free)/total*100)},disk:{total:gb(disk.total),free:gb(disk.free)},cwd:__dirname}}
function createBackup(){fs.mkdirSync(BACKUP_DIR,{recursive:true});const ts=new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);const out=path.join(BACKUP_DIR,`cfbossnusilelo-${ts}.zip`);execFileSync('zip',['-r',out,'public','api','README.md','server.js','-x','*.bak','-x','*/backups/*','-x','*/node_modules/*'],{cwd:__dirname,stdio:'pipe'});return{url:'/backups/'+path.basename(out),size:fs.statSync(out).size}}
function serveChat(res){const html=fs.readFileSync(CHAT_FILE,'utf8');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(html)}
http.createServer((req,res)=>{const url=req.url.split('?')[0],R=wrapRes(res);if(req.method==='GET'&&url==='/api/sys')return R.json(sysInfo());if(req.method==='POST'&&url==='/api/backup'){try{return R.json({ok:true,...createBackup()})}catch(e){return R.status(500).json({error:e.message})}}if(req.method==='POST'&&url==='/api/reload'){try{delete require.cache[require.resolve(path.join(__dirname,'api/chat.js'))];chatRouter=require(path.join(__dirname,'api/chat.js'));return R.json({ok:true,reloaded:new Date().toISOString()})}catch(e){return R.status(500).json({ok:false,error:e.message})}}if(req.method==='GET'&&url.startsWith('/backups/')){const f=path.join(BACKUP_DIR,path.basename(url));if(fs.existsSync(f)){res.writeHead(200,{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="'+path.basename(f)+'"'});return res.end(fs.readFileSync(f))}res.writeHead(404);return res.end('ไม่พบไฟล์สำรอง')}if(req.method==='GET'&&(/^\/chat\/[^/]+\/?$/.test(url)||url==='/chat/living/789'))return serveChat(res);if(req.method==='GET'&&(url==='/'||url==='/chat')){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(fs.readFileSync(HTML_FILE))}let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{req.body=body?JSON.parse(body):{}}catch{req.body={}}try{chatRouter(req,wrapRes(res))}catch(e){R.status(500).json({error:e.message})}})}).listen(process.env.PORT||3000,()=>console.log('CF Bossnusilelo Living 789 on :'+(process.env.PORT||3000)));
